### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by chrishubert** [CodeSlinger69/ClAsHbOt#16]
Code,

Is that me or the training time got longer - especially on the dark barracks.
The icon selection is taking quite long compare to previous releases.

**Comment by CodeSlinger69** [comment]
Not sure what you are referring to here?  Is it that the time it takes to move through all the "Train Troops" screens (7 of them, spells, 4 standard, 2 dark) takes longer?  If so, then yes, it will take marginally longer with this release due to the move to a more robust method of identifying which screen the bot is seeing.  I moved from pixel color detction to image detection, see here: https://github.com/CodeSlinger69/ClAsHbOt/issues/12

However, I saw a moderate increase in the time to move between the screens, and certainly nothing that concerned me.

If it is something else, can you perhaps rephrase your concern and provide more detail?

**Comment by chrishubert** [comment]
It was just a question, not a worry in any way.
Thanks for the answer !
