### ISSUE TITLE
Dump cups always on

### ISSUE THREAD

**Issue by chrishubert** [CodeSlinger69/ClAsHbOt#25]
I have a strange issue since yesterday:
The bot keeps dumping cups even below the threshold:

```
8/26/2015 12:53:15 PM Dumping cups, current=934, threshold=1000
8/26/2015 12:53:15 PM FindAValidMatch()
8/26/2015 12:53:21 PM ControlClickDrag: handle: 00FE0432 380 80 383 379
8/26/2015 12:53:22 PM DeployTroopsToSides()
8/26/2015 12:53:25 PM Error getting end battle confirmation button.
8/26/2015 12:53:28 PM Dumping cups, current=934, threshold=1000
8/26/2015 12:53:28 PM FindAValidMatch()
8/26/2015 12:53:33 PM ControlClickDrag: handle: 00FE0432 500 75 451 398
8/26/2015 12:53:35 PM DeployTroopsToSides()
8/26/2015 12:53:41 PM Dumping cups, current=919, threshold=1000
8/26/2015 12:53:41 PM FindAValidMatch()
8/26/2015 12:53:46 PM ControlClickDrag: handle: 00FE0432 653 400 467 86
8/26/2015 12:53:47 PM DeployTroopsToSides()
8/26/2015 12:53:54 PM Dumping cups, current=903, threshold=1000
8/26/2015 12:53:54 PM FindAValidMatch()
8/26/2015 12:54:02 PM ControlClickDrag: handle: 00FE0432 554 83 522 385
8/26/2015 12:54:04 PM DeployTroopsToSides()
8/26/2015 12:54:10 PM Dumping cups, current=885, threshold=1000
8/26/2015 12:54:10 PM FindAValidMatch()
8/26/2015 12:54:19 PM ControlClickDrag: handle: 00FE0432 597 385 517 80
8/26/2015 12:54:20 PM DeployTroopsToSides()
8/26/2015 12:54:26 PM Dumping cups, current=870, threshold=1000
8/26/2015 12:54:26 PM FindAValidMatch()
```

**Comment by CodeSlinger69** [comment]
That is weird.  Never seen that before, and the log shows you that it shouldn't be happening.  I can't even find a code path that might make that happen.  Very strange, let me know if it recurs.

Unless we can track down a sequence of things that makes this happen, I don't know how to fix, TBH.

**Comment by chrishubert** [comment]
Basically, I troubleshooted it down and it will always have this behaviour whenever your own cups are below 1000.
As soon as I go over 1000 cups it works normally.

**Comment by CodeSlinger69** [comment]
OK, that is one more piece to the puzzle.  Let me snoop around a bit and do some testing.  I might have to create a new account to get my cups under 1000, as I don't want to mess with my main account....

**Comment by CodeSlinger69** [comment]
Simple fix for a stupid error.  Thanks for finding and helping with this, thetitoo.  Essentially, I was doing a string compare, rather than a numeric compare.  In a string compare, "934" is indeed greater than "1000".

The fix is in line 4 and 5 of AutoRaidDumpCups.au3:

```
Local $myCups = Number(GUICtrlRead($GUI_MyCups))
Local $cupsThreshold = Number(GUICtrlRead($GUI_AutoRaidDumpCupsThreshold))
```

Which forces those variables to be numeric type, and thus compared correctly further down in the function.

You'll notice that I already force this conversion in other functions, it just looks like I overlooked this one. A good example is in AutoRaid.au3 in the CheckForRaidableBase() function.

https://github.com/CodeSlinger69/ClAsHbOt/commit/bebdb21ff46aebd7c939dbba1607c8decb648cf0

I'll keep this thread open until the next official release.

**Comment by chrishubert** [comment]
Works perfectly now, thanks! Glad to help as well :)

**Comment by CodeSlinger69** [comment]
Closed.  Fix is in the 9/17 release: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20150917
